name: Portfolio Pipeline

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build the React app
        run: yarn build

      # SET UP DOCKER
      - name: Log in to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Version
        id: version
        run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | head -c 8)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chinjen-react:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chinjen-react:${{ env.IMAGE_TAG }}

      # - name: SSH and Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/chinjen-react:${{ env.IMAGE_TAG }}
      #       docker stop chinjen-react || true
      #       docker rm chinjen-react || true
      #       docker run -d -p 80:80 --name chinjen-react ${{ secrets.DOCKER_USERNAME }}/chinjen-react:${{ env.IMAGE_TAG }}
